//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BitacoraDireccionesIp.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class bdd_bitacora_ipEntities : DbContext
    {
        public bdd_bitacora_ipEntities()
            : base("name=bdd_bitacora_ipEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<tb_bit_cat_area> tb_bit_cat_area { get; set; }
        public DbSet<tb_bit_cat_dga> tb_bit_cat_dga { get; set; }
        public DbSet<tb_bit_cat_empresa> tb_bit_cat_empresa { get; set; }
        public DbSet<tb_bit_cat_equipo_computo_marca> tb_bit_cat_equipo_computo_marca { get; set; }
        public DbSet<tb_bit_cat_equipo_telefono_modelo> tb_bit_cat_equipo_telefono_modelo { get; set; }
        public DbSet<tb_bit_cat_piso> tb_bit_cat_piso { get; set; }
        public DbSet<tb_bit_cat_regional> tb_bit_cat_regional { get; set; }
        public DbSet<tb_bit_cat_switch> tb_bit_cat_switch { get; set; }
        public DbSet<tb_bit_cat_tipo_equipo> tb_bit_cat_tipo_equipo { get; set; }
        public DbSet<tb_bit_cat_wireless> tb_bit_cat_wireless { get; set; }
        public DbSet<tb_bit_ip> tb_bit_ip { get; set; }
        public DbSet<tb_bit_ip_historico> tb_bit_ip_historico { get; set; }
        public DbSet<tb_bit_usuario> tb_bit_usuario { get; set; }
        public DbSet<tb_bit_usuario_historico> tb_bit_usuario_historico { get; set; }
        public DbSet<tb_bt_cat_equipo_computo_modelo> tb_bt_cat_equipo_computo_modelo { get; set; }
    }
}
