//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BitacoraDireccionesIp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_bit_ip_historico
    {
        public int id { get; set; }
        public System.DateTime fecha_cambio { get; set; }
        public string cve_ip { get; set; }
        public int cve_usuario { get; set; }
        public int cve_switch { get; set; }
        public string cve_mac { get; set; }
        public string nom_equipo { get; set; }
        public string nom_resguardo_equipo_computo { get; set; }
        public string cve_equipo_computo_serie { get; set; }
        public int cve_equipo_telefono_extension { get; set; }
        public string cve_equipo_telefono_serie { get; set; }
        public int fk_cve_tipo_equipo { get; set; }
        public int fk_cve_mac_wireless { get; set; }
        public int fk_cve_equipo_computo_marca { get; set; }
        public int fk_cve_equipo_computo_modelo { get; set; }
        public int fk_cve_equipo_telefono_modelo { get; set; }
    
        public virtual tb_bit_cat_equipo_computo_marca tb_bit_cat_equipo_computo_marca { get; set; }
        public virtual tb_bit_cat_equipo_telefono_modelo tb_bit_cat_equipo_telefono_modelo { get; set; }
        public virtual tb_bit_cat_equipo_telefono_modelo tb_bit_cat_equipo_telefono_modelo1 { get; set; }
        public virtual tb_bit_cat_tipo_equipo tb_bit_cat_tipo_equipo { get; set; }
        public virtual tb_bit_cat_wireless tb_bit_cat_wireless { get; set; }
        public virtual tb_bit_cat_switch tb_bit_cat_switch { get; set; }
        public virtual tb_bit_usuario tb_bit_usuario { get; set; }
        public virtual tb_bt_cat_equipo_computo_modelo tb_bt_cat_equipo_computo_modelo { get; set; }
    }
}
