//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BitacoraDireccionesIp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_bit_cat_switch
    {
        public tb_bit_cat_switch()
        {
            this.tb_bit_ip_historico = new HashSet<tb_bit_ip_historico>();
            this.tb_bit_ip = new HashSet<tb_bit_ip>();
        }
    
        public int pk_cve_switch { get; set; }
        public string des_cve_switch { get; set; }
        public string des_puerto { get; set; }
        public string des_roseta { get; set; }
    
        public virtual ICollection<tb_bit_ip_historico> tb_bit_ip_historico { get; set; }
        public virtual ICollection<tb_bit_ip> tb_bit_ip { get; set; }
    }
}
